require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'InforCopRN' do
  config = use_native_modules!
#  use_frameworks!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-openalpr', :path => '../node_modules/react-native-openalpr'

  pod 'react-native-tesseract-ocr', :path => '../node_modules/react-native-tesseract-ocr'

  target 'InforCopRNTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
  use_unimodules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'InforCopRN-tvOS' do
  # Pods for InforCopRN-tvOS

  target 'InforCopRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
